# Generated by Django 4.2.1 on 2023-05-25 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fridgeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_name', models.CharField(blank=True, default='/static/dpp.jpg', max_length=40, null=True)),
                ('display_pic', models.ImageField(blank=True, null=True, upload_to='profiles', verbose_name='profile picture')),
                ('phone_num', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
