# Generated by Django 4.2.1 on 2023-05-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridgeApp', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
