# Generated by Django 4.2.1 on 2023-05-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridgeApp', '0004_items_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='pic',
            field=models.ImageField(blank=True, default='abc.jpg', null=True, upload_to='items_images'),
        ),
    ]
